baseurl = "https://openarteu.github.io"
languageCode = "en-us"
title = "openart blog"
copyright = "openarteu"
canonifyURLs = "true"
googleAnalytics = "UA-23426833-1"

[Author]
	name = "chris"

[Permalinks]
	blog = "/:year/:month/:day/:filename/"

[Taxonomies]
	tag = "tags"

[params]
	description = "remote music education"
	twitter = "https://twitter.com/chrisopart"
	github = "https://github.com/openarteu"
